import Head from "next/head"
import Navbar from './navbar'
import Footer from './footer'

// @ts-ignore
export default function Layout({ children }) {
	return (
		<>
			<Head>
				<title>Qobo</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<Navbar />
			</header>
			<main className="container">
				{children}
				<Footer />
			</main>
		</>
	)
}